version: 1
phases:
  install:
    runtime-versions:
      python: 3.7.0
    commands:
      - aws cloudformation package --template-file samTemplate.yaml --s3-bucket biobeat-staging-cicd-bucket --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - samTemplate.yaml
    - outputSamTemplate.yaml
