AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CICD Test
Resources:
  TestFunction1:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: 'test_function_1'
      Handler: lambda_function.lambda_handler
      Runtime: python3.8
      CodeUri: ./LambdaCode
      Description: 'Test Function 1'
      Role: arn:aws:iam::656606747806:role/lambda_basic_execution
      MemorySize: 128
      Timeout: 30
